site_name: PowerSploit
repo_url: https://github.com/PowerShellMafia/PowerSploit/tree/dev
site_favicon: favicon.ico
pages:
- Home: 'README.md'
    - Recon :
        - Export-PowerViewCSV: 'docs/Recon/Export-PowerViewCSV'
        - Resolve-IPAddress: 'docs/Recon/Resolve-IPAddress'
        - ConvertTo-SID: 'docs/Recon/ConvertTo-SID'
        - ConvertFrom-SID: 'docs/Recon/ConvertFrom-SID'
        - Convert-ADName: 'docs/Recon/Convert-ADName'
        - ConvertFrom-UACValue: 'docs/Recon/ConvertFrom-UACValue'
        - Add-RemoteConnection: 'docs/Recon/Add-RemoteConnection'
        - Remove-RemoteConnection: 'docs/Recon/Remove-RemoteConnection'
        - Invoke-UserImpersonation: 'docs/Recon/Invoke-UserImpersonation'
        - Invoke-RevertToSelf: 'docs/Recon/Invoke-RevertToSelf'
        - Get-DomainSPNTicket: 'docs/Recon/Get-DomainSPNTicket'
        - Invoke-Kerberoast: 'docs/Recon/Invoke-Kerberoast'
        - Get-PathAcl: 'docs/Recon/Get-PathAcl'
        - Get-DomainDNSZone: 'docs/Recon/Get-DomainDNSZone'
        - Get-DomainDNSRecord: 'docs/Recon/Get-DomainDNSRecord'
        - Get-Domain: 'docs/Recon/Get-Domain'
        - Get-DomainController: 'docs/Recon/Get-DomainController'
        - Get-Forest: 'docs/Recon/Get-Forest'
        - Get-ForestDomain: 'docs/Recon/Get-ForestDomain'
        - Get-ForestGlobalCatalog: 'docs/Recon/Get-ForestGlobalCatalog'
        - Find-DomainObjectPropertyOutlier: 'docs/Recon/Find-DomainObjectPropertyOutlier'
        - Get-DomainUser: 'docs/Recon/Get-DomainUser'
        - New-DomainUser: 'docs/Recon/New-DomainUser'
        - Get-DomainUserEvent: 'docs/Recon/Get-DomainUserEvent'
        - Get-DomainComputer: 'docs/Recon/Get-DomainComputer'
        - Get-DomainObject: 'docs/Recon/Get-DomainObject'
        - Set-DomainObject: 'docs/Recon/Set-DomainObject'
        - Get-DomainObjectAcl: 'docs/Recon/Get-DomainObjectAcl'
        - Add-DomainObjectAcl: 'docs/Recon/Add-DomainObjectAcl'
        - Find-InterestingDomainAcl: 'docs/Recon/Find-InterestingDomainAcl'
        - Get-DomainOU: 'docs/Recon/Get-DomainOU'
        - Get-DomainSite: 'docs/Recon/Get-DomainSite'
        - Get-DomainSubnet: 'docs/Recon/Get-DomainSubnet'
        - Get-DomainSID: 'docs/Recon/Get-DomainSID'
        - Get-DomainGroup: 'docs/Recon/Get-DomainGroup'
        - New-DomainGroup: 'docs/Recon/New-DomainGroup'
        - Get-DomainManagedSecurityGroup: 'docs/Recon/Get-DomainManagedSecurityGroup'
        - Get-DomainGroupMember: 'docs/Recon/Get-DomainGroupMember'
        - Add-DomainGroupMember: 'docs/Recon/Add-DomainGroupMember'
        - Get-DomainFileServer: 'docs/Recon/Get-DomainFileServer'
        - Get-DomainDFSShare: 'docs/Recon/Get-DomainDFSShare'
        - Get-DomainGPO: 'docs/Recon/Get-DomainGPO'
        - Get-DomainGPOLocalGroup: 'docs/Recon/Get-DomainGPOLocalGroup'
        - Get-DomainGPOUserLocalGroupMapping: 'docs/Recon/Get-DomainGPOUserLocalGroupMapping'
        - Get-DomainGPOComputerLocalGroupMapping: 'docs/Recon/Get-DomainGPOComputerLocalGroupMapping'
        - Get-DomainPolicy: 'docs/Recon/Get-DomainPolicy'
        - Get-NetLocalGroup: 'docs/Recon/Get-NetLocalGroup'
        - Get-NetLocalGroupMember: 'docs/Recon/Get-NetLocalGroupMember'
        - Get-NetShare: 'docs/Recon/Get-NetShare'
        - Get-NetLoggedon: 'docs/Recon/Get-NetLoggedon'
        - Get-NetSession: 'docs/Recon/Get-NetSession'
        - Get-RegLoggedOn: 'docs/Recon/Get-RegLoggedOn'
        - Get-NetRDPSession: 'docs/Recon/Get-NetRDPSession'
        - Test-AdminAccess: 'docs/Recon/Test-AdminAccess'
        - Get-NetComputerSiteName: 'docs/Recon/Get-NetComputerSiteName'
        - Get-WMIRegProxy: 'docs/Recon/Get-WMIRegProxy'
        - Get-WMIRegLastLoggedOn: 'docs/Recon/Get-WMIRegLastLoggedOn'
        - Get-WMIRegCachedRDPConnection: 'docs/Recon/Get-WMIRegCachedRDPConnection'
        - Get-WMIRegMountedDrive: 'docs/Recon/Get-WMIRegMountedDrive'
        - Get-WMIProcess: 'docs/Recon/Get-WMIProcess'
        - Find-InterestingFile: 'docs/Recon/Find-InterestingFile'
        - Find-DomainUserLocation: 'docs/Recon/Find-DomainUserLocation'
        - Find-DomainProcess: 'docs/Recon/Find-DomainProcess'
        - Find-DomainUserEvent: 'docs/Recon/Find-DomainUserEvent'
        - Find-DomainShare: 'docs/Recon/Find-DomainShare'
        - Find-InterestingDomainShareFile: 'docs/Recon/Find-InterestingDomainShareFile'
        - Find-LocalAdminAccess: 'docs/Recon/Find-LocalAdminAccess'
        - Find-DomainLocalGroupMember: 'docs/Recon/Find-DomainLocalGroupMember'
        - Get-DomainTrust: 'docs/Recon/Get-DomainTrust'
        - Get-ForestTrust: 'docs/Recon/Get-ForestTrust'
        - Get-DomainForeignUser: 'docs/Recon/Get-DomainForeignUser'
        - Get-DomainForeignGroupMember: 'docs/Recon/Get-DomainForeignGroupMember'
        - Get-DomainTrustMapping: 'docs/Recon/Get-DomainTrustMapping'
        - Get-ComputerDetails: 'docs/Recon/Get-ComputerDetails'
        - Get-HttpStatus: 'docs/Recon/Get-HttpStatus'
        - Invoke-Portscan: 'docs/Recon/Invoke-Portscan'
        - Invoke-ReverseDnsLookup: 'docs/Recon/Invoke-ReverseDnsLookup'
- About:
    - License: 'LICENSE.md'